name: posts_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  animated_text_kit:
  flame_splash_screen: ^0.1.0
  awesome_card: ^1.1.7
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  collection: ^1.16.0
  coupon_uikit: ^0.2.0
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  easy_image_viewer: ^1.2.0
  easy_localization: ^3.0.1
  firebase_core: ^2.12.0
  firebase_messaging: ^14.1.3
  firebase_auth: ^4.1.5
  firebase_database: ^10.0.6
  flutter_animarker: ^3.2.0
  flutter_breadcrumb: ^1.0.1
  flutter_form_builder: ^9.1.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  form_builder_validators: ^9.0.0
  google_maps_flutter: ^2.2.1
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  introduction_screen: ^3.1.1
  label_marker: ^1.0.1
  location: ^5.0.3
  phone_form_field: ^8.1.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.4
  slide_countdown: ^0.6.0
  sticky_headers: ^0.3.0+2
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.1.7
  webview_flutter: ^4.2.4
  smooth_page_indicator: ^1.0.1
  curved_navigation_bar: ^1.0.3
  scrollable_list_tabview: ^0.2.0-nullsafety
  sizer: ^2.0.15
  flutter_neumorphic: ^3.2.0
  vertical_weight_slider: ^2.5.0
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^5.0.0
  progress_indicator: ^0.2.2
  get: ^4.6.5
  inkblob_navigation_bar: ^0.1.2
  flutter_local_notifications: ^15.1.1
  toast: ^0.3.0
  fluttertoast: ^8.2.1
  flutter_dialogs: ^3.0.0
  bdd_widget_test: ^1.6.0
  connectivity: ^3.0.6
  in_app_update: ^4.1.4
  upgrader: any
  geocoding: ^2.1.0
  sweet_nav_bar: ^1.0.5
  smooth_star_rating_null_safety: ^1.0.4+2
  modal_progress_hud_nsn: ^0.3.0


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  rename: ^2.0.1
  test: ^1.22.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icon/

  fonts:
    - family: nunito-sans.bold
      fonts:
        - asset: assets/fonts/nunito-sans.bold.ttf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"

#
#flutter_native_splash:
#  color: "#F0262C"
#  # image: assets/icon/icon_transparent.png
#  android: true
#  ios: true