name: posts_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  flutter_form_builder: ^9.1.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  form_builder_validators: ^9.0.0
  image_picker: ^1.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.4
  top_snackbar_flutter: ^3.1.0
  sizer: ^2.0.15
  modal_progress_hud_nsn: ^0.3.0


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  rename: ^2.0.1
  test: ^1.22.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"

#
#flutter_native_splash:
#  color: "#F0262C"
#  # image: assets/icon/icon.png
#  android: true
#  ios: true